
[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[dependencies]]
  branch = "master"
  name = "github.com/kennygrant/sanitize"

[[dependencies]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"
