
[[dependencies]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[dependencies]]
  branch = "master"
  name = "github.com/kennygrant/sanitize"
