
[[constraint]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[constraint]]
  branch = "master"
  name = "github.com/kennygrant/sanitize"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"
